export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const CLEAR_CART = 'CLEAR_CART'
export const ADD_SHIPPING_DETAILS = 'ADD_SHIPPING_DETAILS'
export const ADD_PAYMENT_METHOD = 'ADD_PAYMENT_METHOD'
export const ORDER_DETAILS = 'ORDER_DETAILS'
export const SET_USER_INFO = 'SET_USER_INFO';
